import os
import re
from dotenv import load_dotenv
from crewai import Crew
from tasks import GameTasks
from agents import GameAgents

# Load environment variables
load_dotenv()

# Initialize tasks and agents
tasks = GameTasks()
agents = GameAgents()

print("## Welcome to the Game Crew")
print("-------------------------------")
game_description = input("What is the game you would like to build? What will be the mechanics?\n")

# Create Agents
senior_engineer_agent = agents.senior_engineer_agent()
qa_engineer_agent = agents.qa_engineer_agent()
chief_qa_engineer_agent = agents.chief_qa_engineer_agent()

# Create Tasks
code_game = tasks.code_task(senior_engineer_agent, game_description)
review_game = tasks.review_task(qa_engineer_agent, game_description)
approve_game = tasks.evaluate_task(chief_qa_engineer_agent, game_description)

# Create Crew
crew = Crew(
    agents=[senior_engineer_agent, qa_engineer_agent, chief_qa_engineer_agent],
    tasks=[code_game, review_game, approve_game],
    verbose=True,
)

# Run the crew
final_game_code = crew.kickoff()

print("\n\n########################")
print("## Game Generated Successfully 🎮")
print("########################\n")

# Convert to string (CrewOutput → text)
final_game_code_str = str(getattr(final_game_code, "output", final_game_code))

# Try extracting Python code from ```python ... ```
code_match = re.search(r"```python(.*?)```", final_game_code_str, re.DOTALL)

if code_match:
    extracted_code = code_match.group(1).strip()

    with open("generated_game.py", "w", encoding="utf-8") as f:
        f.write(extracted_code)

    print("✅ Code saved to generated_game.py")
    print("🚀 Running the game now...\n")

    os.system("python generated_game.py")
else:
    print("⚠️ No valid Python code was generated by the crew.")
    print("Raw output was:\n")
    print(final_game_code_str)
